obj_pdb_result = {
    '1fp9': 'AMYLOMALTASE',
    '1gln': 'GLUTAMYL-TRNA SYNTHETASE',
    '1h3n': 'Leucyl-tRNA synthetase',
    '1h4v': 'HISTIDYL-TRNA SYNTHETASE',
    '1hex': '3-ISOPROPYLMALATE DEHYDROGENASE',
    # '1ile': 'ISOLEUCYL-TRNA SYNTHETASE',
    '1iom': 'CITRATE SYNTHASE',
    '1ipa': 'RNA 2\'-O RIBOSE METHYLTRANSFERASE',
    '1iq0': 'ARGINYL-TRNA SYNTHETASE',
    '1iqr': 'DNA photolyase',
    '1iqu': 'photolyase-thymine',
    '1ir6': 'exonuclease RecJ',
    '1iyz': 'Quinone Oxidoreductase',
    '1kwg': 'A4 beta-galactosidase',
    '1nox': 'NADH OXIDASE',
    '1od6': 'Phosphopantetheine adenylyltransferase',
    '1tuo': 'phosphomannomutase',
    '1uar': 'Rhodanese',
    '1ub0': 'Phosphomethylpyrimidine Kinase (ThiD)',
    '1ug6': 'beta-glucosidase',
    '1ui0': 'Uracil-DNA Glycosylase',
    '1uiy': 'Enoyl-CoA Hydratase',
    '1uj4': 'ribose-5-phosphate isomerase',
    '1v2d': 'Glutamine Aminotransferase',
    '1v2x': 'tRNA (Gm18) methyltransferase',
    '1v8e': 'Glycerophosphoryl Diester Phosphodiesterase',
    '1v8i': 'ADP-ribose pyrophosphatase',
    # '1v93': '5,10-Methylenetetrahydrofolate Reductase',
    '1vbi': 'type 2 malate/lactate dehydrogenase',
    '1vc2': 'Glyceraldehyde 3-Phosphate Dehydrogenase',
    '1vcm': 'CTP synthetase',
    '1vd6': 'Glycerophosphoryl Diester Phosphodiesterase',
    '1ve1': 'O-acetylserine sulfhydrylase',
    '1ve4': 'ATP-Phosphoribosyltransferase(hisG)',
    '1wcv': 'bacterial chromosome segregation protein Soj',
    '1wcw': 'Uroporphyrinogen III Synthase',
    '1wf3': 'GTP-binding protein TT1341',
    '2cb1': 'O-actetyl Homoserine Sulfhydrylase',
    '2cu2': 'mannose-1-phosphate geranyltransferase',
    '2czl': 'a menaquinone biosynthetic enzyme',
    '2d2e': 'ABC-ATPase SufC',
    '2d3y': 'uracil-DNA glycosylase',
    # '2e7u': 'glutamate-1-semialdehyde 2,1-aminomutase',
    '2yev': 'caa3-type cytochrome oxidase',
    '2eco': 'O-acetylserine sulfhydrylase',
    '2ef0': 'ornithine carbamoyltransferase',
    '2ef4': 'arginase'
}